### ISSUE TITLE
Fazer análise estática do código com Rubocop

### ISSUE THREAD

**Issue by samycici** [DarlingL/testcapybara#2]
Usar o https://github.com/bbatsov/rubocop e corrigir as ofensas detectadas (que fizerem sentido)

**Comment by DarlingL** [comment]
Quando executei a primeira vez tinha 50 ofensas, após alterações sobraram 1.


Offenses:

features/support/env.rb:5:39: C: Use the new Ruby 1.9 hash syntax.
  Capybara::Selenium::Driver.new(app, :browser => :chrome)
                                      ^^^^^^^^^^^

4 files inspected, 1 offense detected

**Comment by samycici** [comment]
Isso é da implementação do browser mesmo, pode deixar assim
