### ISSUE TITLE
passar o termo de pesquisa na feature

### ISSUE THREAD

**Issue by samycici** [DarlingL/testcapybara#7]
o termo de pesquisa 'Cruzeiro Globo Esporte' vai ser passado na feature como argumento pro step e pro page object, ao invés de ficar no page object

**Comment by DarlingL** [comment]
o Step ficou assim: 

_**Quando(/^realizada uma busca por (.*)$/) do |cruzeiro|
  @googleactions.busca(cruzeiro) 
end**_

 e o metodo assim:

  _**def busca (cruzeiro)
    @cruzeiro = cruzeiro
    fill_in id: 'lst-ib', with: @cruzeiro
    find(:id, 'hplogo').click
    find('[name=btnK]').click
  end**_

**Comment by samycici** [comment]
Coloca na feature o termo Cruzeiro Globo Esporte entre aspas.

**Comment by DarlingL** [comment]
Atualizei
