### ISSUE TITLE
localiza o botão de pesquisa pelo name dele ao invés do xpath

### ISSUE THREAD

**Issue by samycici** [DarlingL/testcapybara#9]

**Comment by DarlingL** [comment]
Ficou assim o metodo: 

_**def busca (cruzeiro)
@Cruzeiro = cruzeiro
fill_in id: 'lst-ib', with: @Cruzeiro
find(:id, 'hplogo').click
find('[name=btnK]').click
end**_


usei esse link como apoio:

https://stackoverflow.com/questions/22371151/capybara-wont-find-a-button-by-its-name-attribute
